### ISSUE TITLE
Database Support

### ISSUE THREAD

**Issue by 0x27** [s-rah/onionscan#27]
As a follow-on from https://github.com/s-rah/onionscan/issues/3, it would be interesting to have an option to connect results and scanning up to a database.

Correlating data across multiple onions can lead to some amusing results. Such as finding that a bunch of onions all share the same SSH fingerprint (hosting providers...) where the data by itself is not much help, but when you correlate it all, you end up being able to deanonymize a whole cluster of onions in one go because one of the hosts on the server is leaking something interesting.

This could be connected up to external API's such as Shodan somehow on a schedule with re-checking of things like SSH keys, etc every now and then.

**Comment by s-rah** [comment]
In order to get anywhere on #73 we need a proper database design (inspired by #84 but here seemed a better placed.)

Despite introducing it I'm still not 100% sold on using tiedot. Undoubtedly OnionScan needs a DB and right now tiedot serves it's purpose for realizing some of the 0.2 stuff.

Thinking ahead there are a few usecases for an OnionScan db that are better suited to a traditional db rather than a nosql solution:

* Correlations: Ideally we should be able to correlate across any identifier in any part of the record that we save - this is fairly simple, if potentially inefficient to do dynamically with sql solutions - nosql, not so much.
* On a related point, tiedot's indexes are not that great - and there is a fair amount of behind the scenes code we will have to write to wire things together.
* Another related point: Fuzzy Searching / Dynamic Identifier Analysis - I can certainly see cases in teh future where we might want to automatically detect identifiers e.g. custom analytics code.

However, it would be nice if users, especially casual ones, don't have mess around with setting up a db. I am only familiar with https://github.com/cznic/ql in this space - and it certainly isn't as mature as tiedot.

So right now I am torn, I am going to try and write a fuller DB design requirements doc in the coming days to try and wrap my head around exactly what we should aim to build.
